--------------------------------------------------------------------------------------
-- UNIVERSAL SCHEMA (H2 & PostgreSQL Compatible)
-- This single file works for both databases with platform-specific syntax handling
--------------------------------------------------------------------------------------

-- Drop existing tables (if any)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;

--------------------------------------------------------------------------------------
-- TABLE DEFINITIONS
--------------------------------------------------------------------------------------

-- PRODUCTS TABLE
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock_quantity INT NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    version BIGINT DEFAULT 0
);

-- ORDERS TABLE
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    total_amount NUMERIC(19,2) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
    created_at TIMESTAMP NOT NULL
);

-- PAYMENTS TABLE
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    amount NUMERIC(19,2) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','COMPLETED','FAILED','REFUNDED')),
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('CREDIT_CARD','DEBIT_CARD','PAYPAL','BANK_TRANSFER')),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- ORDER ITEMS TABLE
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);

-- Create indexes for better query performance
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_payments_order_id ON payments(order_id);

--------------------------------------------------------------------------------------
-- SAMPLE DATA INSERTION (WITHOUT EXPLICIT IDs)
-- Let the database auto-generate all IDs
--------------------------------------------------------------------------------------

-- PRODUCTS (IDs will be auto-generated: 1, 2, 3, 4, 5)
INSERT INTO products (name, stock_quantity, price) VALUES
('Wireless Mouse', 120, 25.50),
('Mechanical Keyboard', 75, 80.00),
('USB-C Hub', 60, 45.99),
('27-inch Monitor', 40, 230.00),
('Laptop Stand', 90, 35.00);

-- ORDERS (IDs will be auto-generated: 1, 2, 3, 4, 5, 6)
INSERT INTO orders (customer_id, total_amount, status, created_at) VALUES
(101, 105.50, 'CONFIRMED', TIMESTAMP '2025-10-01 10:32:00'),
(102, 230.00, 'PENDING', TIMESTAMP '2025-10-03 15:45:00'),
(103, 160.99, 'SHIPPED', TIMESTAMP '2025-10-05 09:12:00'),
(104, 45.99, 'CANCELLED', TIMESTAMP '2025-10-06 17:20:00'),
(101, 115.00, 'DELIVERED', TIMESTAMP '2025-10-08 12:10:00'),
(105, 1245.00, 'CONFIRMED', TIMESTAMP '2025-10-12 11:15:00');

-- ORDER ITEMS (IDs will be auto-generated: 1-11)
-- Note: order_id and product_id reference the auto-generated IDs above
INSERT INTO order_items (order_id, product_id, quantity, price) VALUES
-- Order 1 items
(1, 1, 2, 25.50),
(1, 5, 1, 35.00),
-- Order 2 items
(2, 4, 1, 230.00),
-- Order 3 items
(3, 2, 2, 80.00),
(3, 3, 1, 45.99),
-- Order 4 items
(4, 3, 1, 45.99),
-- Order 5 items
(5, 1, 1, 25.50),
(5, 5, 2, 35.00),
-- Order 6 items
(6, 4, 3, 230.00),  -- 3 Monitors × 230 = 690.00
(6, 2, 5, 80.00),   -- 5 Keyboards × 80 = 400.00
(6, 3, 3, 51.67);   -- 3 USB-C Hubs × 51.67 = 155.00

-- PAYMENTS (IDs will be auto-generated: 1-6)
INSERT INTO payments (order_id, amount, status, payment_method) VALUES
(1, 105.50, 'COMPLETED', 'CREDIT_CARD'),
(2, 230.00, 'PENDING', 'PAYPAL'),
(3, 160.99, 'COMPLETED', 'CREDIT_CARD'),
(4, 45.99, 'FAILED', 'CREDIT_CARD'),
(5, 115.00, 'REFUNDED', 'DEBIT_CARD'),
(6, 1245.00, 'COMPLETED', 'BANK_TRANSFER');

--------------------------------------------------------------------------------------
-- VERIFICATION QUERIES (commented out - uncomment to test)
--------------------------------------------------------------------------------------
-- SELECT 'Products Count: ' || COUNT(*) FROM products;
-- SELECT 'Orders Count: ' || COUNT(*) FROM orders;
-- SELECT 'Order Items Count: ' || COUNT(*) FROM order_items;
-- SELECT 'Payments Count: ' || COUNT(*) FROM payments;